In [1]:
import numpy as np

In [2]:
A = np.asarray([[1,2], [3,4]])

In [3]:
np.dot(A, A)

array([[ 7, 10],
       [15, 22]])

In [9]:
np.sum(np.multiply(A, A), axis=1)

array([ 5, 25])

In [11]:
np.average(np.sum(np.multiply(A, A), axis=1))

15.0

In [18]:
B = np.ndarray(shape=(10, 2))
for i in range(B.shape[0]):
    B[i, :] = [i, i]

In [19]:
B

array([[ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.],
       [ 4.,  4.],
       [ 5.,  5.],
       [ 6.,  6.],
       [ 7.,  7.],
       [ 8.,  8.],
       [ 9.,  9.]])

In [23]:
idx = [0,1,2,3,4,5,6,7,8,9,9,8,7,6,5,4,3,2,1,0]
C = np.take(B, idx, axis=0)

In [24]:
C

array([[ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.],
       [ 4.,  4.],
       [ 5.,  5.],
       [ 6.,  6.],
       [ 7.,  7.],
       [ 8.,  8.],
       [ 9.,  9.],
       [ 9.,  9.],
       [ 8.,  8.],
       [ 7.,  7.],
       [ 6.,  6.],
       [ 5.,  5.],
       [ 4.,  4.],
       [ 3.,  3.],
       [ 2.,  2.],
       [ 1.,  1.],
       [ 0.,  0.]])

In [7]:
arr = []
d = 6
arr_test(arr, d)
arr

[6]

In [10]:
A = np.asarray([1, 2, 3])

In [19]:
B = A / np.linalg.norm(A)

In [21]:
B
np.linalg.norm(B)

1.0